spring:
  application:
    name: greeting

server:
  port: 8080

greeting:
    displayFortune: true
    printMsg: "Got values from property file!!!"

fortune:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule 